# Label configuration for PR auto-labeling

# Backend changes
backend:
  - backend/**/*

# Frontend changes
frontend:
  - frontend/**/*

# Database changes
database:
  - backend/src/database/**/*
  - backend/drizzle/**/*
  - backend/database/**/*

# Testing
tests:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/__tests__/**/*'

# Configuration
config:
  - '**/*.config.js'
  - '**/*.config.ts'
  - '**/tsconfig.json'
  - '**/package.json'

# Documentation
documentation:
  - '**/*.md'
  - 'docs/**/*'

# CI/CD
ci:
  - '.github/**/*'

# Docker
docker:
  - '**/Dockerfile'
  - '**/docker-compose.yml'
  - '**/.dockerignore'
  - '**/nginx.conf'

# Dependencies
dependencies:
  - '**/package.json'
  - '**/package-lock.json'
  - '**/bun.lock'
